import { SurveyDetail } from "./types";

export const SURVEY_QUESTION: SurveyDetail[] = [
  {
    id: "1",
    navi: "여행 성향",
    question: "나 혼자 여행을 간다면?",
    type: "single",
    options: ["온 세상이 내 친구", "나홀로 단단한 여행"],
  },
  {
    id: 2,
    navi: "여행 성향",
    question: "여행을 다녀와서 생각나는 건?",
    type: "single",
    options: ["맛있게 먹은 음식 이름", "행복했던 기분과 그때의 분위기"],
  },
  {
    id: 3,
    navi: "여행 성향",
    question: "여행 중 돌발상황이 생기면?",
    type: "single",
    options: ["최적의 선택을 고민", "이것도 추억이 되겠지"],
  },
  {
    id: 4,
    navi: "여행 성향",
    question: "여행을 가서는?",
    type: "single",
    options: ["계획에 따라 움직임", "즉흥적으로 융통성 있게"],
  },
  {
    id: 5,
    navi: "술 취향",
    question: "좋아하는 술은?",
    type: "single",
    options: ["막걸리", "소주", "맥주", "위스키", "와인", "하이볼"],
  },
  {
    id: 6,
    navi: "술 취향",
    question: "좋아하는 음식은?",
    type: "single",
    options: ["짜장", "보쌈", "곱창/대창", "손두부찌개", "냉소면", "두루치기"],
  },
  {
    id: 7,
    navi: "술 취향",
    question: "술이 땡기는 날은?",
    type: "single",
    options: [
      "내가 오늘 넘 수고",
      "누군가와 컨텐츠한 식후 땡",
      "슬플 때",
      "비교적 자주",
    ],
  },
  {
    id: 8,
    navi: "개인정보",
    question: "사용 가능한 언어는? (중복 가능)",
    type: "multi",
    options: ["한국어", "영어", "일본어", "중국어"],
  },
  {
    id: 9,
    navi: "개인정보",
    question: "현재 직업은?",
    type: "single",
    options: [
      "요식,서비스에 단발성 알바",
      "토크,기획에 단발성 알바",
      "시험을 앞두고, 미치는 중",
      "전문직, 학술직 알바",
      "신입무직이지만 일하고 싶다",
    ],
  },
  {
    id: 10,
    navi: "개인정보",
    question: "내 국적은?",
    type: "single",
    options: ["한국", "일본", "중국", "대만", "독일", "기타"],
  },
  {
    id: 11,
    navi: "개인정보",
    question: "현재 연애 상태",
    type: "single",
    options: ["솔로", "커플"],
  },
] as const;
