import type { Metadata } from "next";
import "./globals.css";
import { SessionProvider } from "@/widgets/provider";
import ReactQueryProvider from "@/widgets/provider/ReactQueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css"
        />
      </head>

      <body>
        <div className="w-[375px] h-[812px] mx-auto bg-white flex flex-col">
          <SessionProvider>{children}</SessionProvider>
        </div>
      </body>
    </html>
  );
}
